---
game:
  version: 0.0.1
  author: Sye
  debug: true
actors:
  - name: base
    render:
      texture: carrot
    physic:
      bounding_box: circle
  - name: ball
    render:
      texture: carrot
      scale: 0.25
    physic:
      bounding_box: circle
  - name: wall
    render:
      sprite_type: tiling sprite
      texture: rock
      size:
        w: 1000
        h: 30
      rotation: 0.1
    physic:
      bounding_box: rectangle
      static: true
assets:
  textures:
...